
name: Neuroscitechie, introspections on on Machine Learning, Deep Learning and PhD Learning..
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
github_username:     meltem-ai
medium_username:     neuroscitech
twitter_username:    MeltemAI
linkedin-username:   meltematay
meetup_username:     211539050
google_analytics:    UA-115611361-1
