
name: Introspections on on Machine Learning, Deep Learning and PhD Learning..
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
github_username:     meltemiatay
medium_username:     meltematay
twitter_username:    meltamiataynsnt
linkedin_username:   meltematay
google_analytics:    UA-115611361-1
