
name: Perspective about Machine Learning, Deep Learning and PhD Learning..
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
title: [Meltem's Site]
description: [Summary of the learning]
github_username:     meltemiatay
medium_username:     meltematay
twitter_username:    meltemataynsnt
linkedin_username:   meltematay
google_analytics:    UA-115611361-1
